/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package fr.dzzd.glsprite;



import java.util.HashMap;
import java.util.Vector;
import java.util.Enumeration;

import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollObject;
import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import android.app.Activity;


// This proxy can be created by calling Glsprite.createGLView({message: "hello world"})
@Kroll.proxy(creatableInModule=GlspriteModule.class)
public class GLViewProxy extends TiViewProxy implements GLViewListener
{
	// Standard Debugging variables
	private static final String LCAT = "ExampleProxy";
	private static final boolean DBG = TiConfig.LOGD;

    private KrollFunction onCreatedCallback = null;
    private KrollFunction onChangedCallback = null;
    private KrollFunction onDrawCallback = null;

	public TIGLView tiGlView;

	// Constructor
	public GLViewProxy()
	{
		super();
	}

	@Override
	public TiUIView createView(Activity activity)
	{
		Log.i("GLSprite", "GLViewProxy.createView(activity)");
		this.tiGlView = new TIGLView(this);
		return this.tiGlView;
	}
/*
	public class TView extends TiUIView
	{

		public TView(GLViewProxy proxy, Activity activity)
		{
			super(proxy);
			proxy.glView = new GLView();
			this.setNativeView(proxy.glView);
			this.getLayoutParams().autoFillsHeight = true;
			this.getLayoutParams().autoFillsWidth = true;

			Log.i("GLSprite", "TView(TiViewProxy, GLView)");

		}
	}
*/
	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options)
	{
		super.handleCreationDict(options);

		Log.i("GLSprite", "GLViewProxy.handleCreationDict(KrollDict)");

		if (options.containsKey("message")) 
		{
			Log.i("GLSprite", "GLViewProxy.handleCreationDict(KrollDict) => option.containsKey('message')");
		}
		
		if (options.containsKey("oncreated")) 
		{
			this.setOncreated(options.get("oncreated"));
		}

		if (options.containsKey("onchanged")) 
		{
			this.setOnchanged(options.get("onchanged"));
		}
		
		if (options.containsKey("ondraw")) 
		{
			this.setOndraw(options.get("ondraw"));
		}
	}



    public void onCreated()
    {
		this.fireEvent("created", new Object());
		if(this.onCreatedCallback != null)
		{
			HashMap<String, String> event = new HashMap<String, String>();
    		this.onCreatedCallback.call(this.getKrollObject(), event);
		}

    }
    
    public void onChanged(int width, int height)
    {
		HashMap<String, String> event = new HashMap<String, String>();
		event.put("width", String.valueOf(width));
		event.put("height", String.valueOf(height));

		this.fireEvent("changed", event);
		if(this.onChangedCallback != null)
		{
    		this.onChangedCallback.call(this.getKrollObject(), event);
		}
        
        
	}
	
    
    public void onDraw()
    {
		this.fireEvent("draw", new Object());
		if(this.onDrawCallback != null)
		{
			HashMap<String, String> event = new HashMap<String, String>();
    		this.onDrawCallback.call(this.getKrollObject(), event);
		}
        
	}
	
	@Kroll.method
	public void setEntityPos(int index, float x, float y, float r, float sx, float sy, float px, float py)
	{
		GLEntity glEntity =  this.getScene().getChildAt(index);
		glEntity.x = x;
		glEntity.y = y;
		glEntity.r = r;
		glEntity.sx = sx;
		glEntity.sy = sy;
		glEntity.px = px;
		glEntity.py = py;
	}

	
	@Kroll.method
	public void setEntityPos(int index[], float x[], float y[], int count)//, float r, float sx, float sy, float px, float py)
	{
		Vector<GLEntity> flattenedEntities = new Vector<GLEntity>();
		this.getScene().getFlattenedEntities(flattenedEntities);
		for(int n = 0; n<count;n++)
		{
			GLEntity glEntity =  this.getScene().getChildAt(index[n]);
			glEntity.x=x[n];
			glEntity.y=y[n];
		}
	}

	@Kroll.method
	public KrollDict[] getFullScene()
	{
		Vector<KrollDict> v = new Vector<KrollDict>();
		this.getScene().getProperties(v);
		KrollDict[] k = new KrollDict[v.size()];

		int n =0;
		for (Enumeration<KrollDict> e = v.elements(); e.hasMoreElements();)
        {
            k[n++]=e.nextElement();
		}
		return k;
	}

	


	@Kroll.method
	public int testPerf(int test)
	{
		return test+1;
	}

	@Kroll.method
	public Object createGLSprite(String filePath)
	{
		Log.i("GLSprite", "ExampleProxy.createGLSprite(" + filePath + ")");
		return new GLSprite(filePath);
	}

	@Kroll.method
	public GLScene getScene()
	{
		//Log.i("GLSprite", "ExampleProxy.getScene()");
		return this.tiGlView.getScene();
	}

	@Kroll.method
	public void addSprite(KrollDict options)
	{
		GLSprite sprite = new GLSprite((String)options.get("url"), options);
		this.tiGlView.getScene().add(sprite);
	}

	@Kroll.method
	public void addSprite2()
	{
	}

	@Kroll.method
	public void updateBulkModeXY(int[] datas, boolean packetFull)
	{
		this.tiGlView.getScene().updateBulkModeXY(datas, packetFull);
	}
	
	/*
	@Kroll.method
	public GLEntity getScene()
	{
		return this.glView.getScene();
	}
	*/

	
	@Kroll.setProperty @Kroll.method
	public void setOncreated(Object callback)
	{
		Log.i("GLSprite", "ExampleProxy.setOncreated(callback)");
		this.onCreatedCallback = (KrollFunction)callback;
	}

	
	@Kroll.setProperty @Kroll.method
	public void setOnchanged(Object callback)
	{
		Log.i("GLSprite", "ExampleProxy.setOnchanged(callback)");
		this.onChangedCallback = (KrollFunction)callback;
	}


	@Kroll.setProperty @Kroll.method
	public void setOndraw(Object callback)
	{
		Log.i("GLSprite", "ExampleProxy.setOndraw(callback)");
		this.onDrawCallback = (KrollFunction)callback;
	}

	


	@Kroll.getProperty @Kroll.method
	public String getMessage()
	{
        return "Hello World from my module";
	}

	@Kroll.setProperty @Kroll.method
	public void setMessage(String message)
	{
	    Log.i("GLSprite", "ExampleProxy.setMessage(" + message + ")");
	}

	@Kroll.method
	public void printMessage(String message)
	{
	    Log.i("GLSprite", "ExampleProxy.printMessage(" + message + ")");
	}
}
